SELC-2668 e SELC-2666
pagopa/selfcare-ms-core pull request #160
Opened 2023-07-24 10:22 UTC by empassaro

2023-07-24 12:19 UTC, manuraf commented
Title and description don't follow our convention template (https://github.com/pagopa/selfcare-ms-core/blob/main/.github/PULL_REQUEST_TEMPLATE.md). For example, look at https://github.com/pagopa/selfcare-ms-core/pull/144

2023-07-24 12:21 UTC, manuraf requested changes
Title and description don't follow our convention template (https://github.com/pagopa/selfcare-ms-core/blob/main/.github/PULL_REQUEST_TEMPLATE.md). For example, look at https://github.com/pagopa/selfcare-ms-core/pull/144

2023-07-25 09:37 UTC, empassaro commented on core/src/main/java/it/pagopa/selfcare/mscore/core/UserRelationshipServiceImpl.java
@KevinSi96 Ho effettuato un merge dei tuoi sviluppi con i nostri. Quando hai un attimo puoi controllare sia tutto ok anche per te?

2023-07-26 10:42 UTC, manuraf requested changes

2023-07-26 10:42 UTC, manuraf commented on connector-api/src/test/java/it/pagopa/selfcare/mscore/exception/ResourceForbiddenExceptionTest.java
> +
we could avoid to test the exception classess

2023-07-26 10:42 UTC, manuraf commented on connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImplTest.java
> +        onboarding.setPricingPlan("pricingPal");
we could avoid to replicate the same definition of an object for each test method....you might implement an utility test (es. createDummy PaymentServiceProvider) that create a dummy object with default value for each attribute and using that when you need a dummy object for test.....look at https://github.com/pagopa/selfcare-ms-core/blob/main/web/src/test/java/it/pagopa/selfcare/mscore/web/TestUtils.java

2023-07-26 10:42 UTC, manuraf commented on connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImplTest.java
> +        institutionEntity.setZipCode("21654");
ditto

2023-07-26 10:42 UTC, manuraf commented on core/src/test/java/it/pagopa/selfcare/mscore/core/UserNotificationServiceImplTest.java
> +        user1.setEmail(nome);
ditto

2023-07-26 13:27 UTC, manuraf commented on connector-api/src/test/java/it/pagopa/selfcare/mscore/exception/ResourceForbiddenExceptionTest.java
> +
you might remove only this

2023-07-28 13:21 UTC, andrea-putzu approved these changes

2023-07-31 06:49 UTC, manuraf approved these changes

2023-07-31 07:16 UTC, merged