SELC-3291 Added strategy to create institutions from tool
pagopa/selfcare-ms-core pull request #285
Opened 2023-10-27 11:24 UTC by empassaro

#### List of Changes

Added API for creation of institution used by selfcare-pagopa-injestion tool. The API persist institutions data collecting informations on IPA and Infocamere registries.

#### Motivation and Context

Added API for creation of institution to allow the selfcare-pagopa-injestion tool to allow ECs and PTs to join the prod-pagopa product by collecting data from IPA or Infocamere.

#### How Has This Been Tested?
Tested in local environment.

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-10-27 14:02 UTC, manuraf requested changes

2023-10-27 14:14 UTC, flaminiaScarciofolo commented on core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyPda.java
> +        if(injestionInstitutionType.equalsIgnoreCase("PT")) {
non è stato usato l'institutionType per differenziare, perchè questo parametro prescinde dall'institutionType nel caso ad esempio di EC, è un campo che viene inviato dal tool per indicare se si tratta di EC o di PT. Nel caso di EC poi l'institutionType assumerà il valore PA oppure il valore PG

2023-10-27 16:15 UTC, empassaro commented on core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyPda.java
Following this tip we would face another problem. We should change a bit the IPA strategy in order to persist data as we do now with PDA strategy, and Infocamere strategy is already a class we are supposed to release for an opened bug, but it has a bit different workflow when institution is not found on infocamere. This Strategy and relative API will be removed after using the PDA tool, So in order to avoid complexity and branches on actual Strategies is probably easier to keep them separated.

2023-10-30 10:06 UTC, manuraf approved these changes

2023-10-30 10:36 UTC, merged